### ISSUE TITLE
Encoding previously decoded gif results in different looking gif

### ISSUE THREAD

**Issue by ArtBIT** [jtlapp/gifwrap#17]
Here's a minimal example that illustrates this issue. It loads a gif image, decodes it and then immediately encodes it as a new image, which ends up looking completely different from the input image:
```
var fs = require("fs");
var path = require("path");
var GifCodec = require("gifwrap").GifCodec;

fs.readFile(path.join(__dirname, "./input.gif"), (err, buffer) => {
  if (err) throw err;
  var codec = new GifCodec();
  codec.decodeGif(buffer).then(gif => {
    codec
      .encodeGif(gif.frames, {
        loops: gif.loops,
        colorScope: gif.colorScope
      })
      .then(gif => {
        fs.writeFileSync(path.join(__dirname, "./output.gif"), gif.buffer);
      });
  });
});

```
## input.gif
<img src="https://user-images.githubusercontent.com/184220/47577245-b278cf00-d946-11e8-8b30-bc7e948f9f10.gif" alt="input.gif" width="200"/>

## output.gif
<img src="https://user-images.githubusercontent.com/184220/47577246-b278cf00-d946-11e8-8b26-31a2500ef04a.gif" alt="output.gif" width="200" />

I have noticed similar behaviour with gifs that have frames with x and/or y offsets.

**Comment by jtlapp** [comment]
I just tested this with the latest version of gifwrap. If it wasn't working before, it is working now. Perhaps #18 fixed it. Thanks for reporting the problem. Let me know if it still persists.

**Comment by ArtBIT** [comment]
It works for me as well with v0.9.2

**Comment by jtlapp** [comment]
Excellent! Thanks for checking.
