### ISSUE TITLE
question: Is there any reason we can't use floats like 1.5 on scale?

### ISSUE THREAD

**Issue by KingDGrizzle** [jtlapp/gifwrap#4]
I've recently messed around with this module ~~and a few animated emojis on Discord~~.  And while having a blast, I couldn't help but notice we can't scale with numbers like `1.5`

Is there any reason for this? Is it just because floats can do weird stuff, or is this a limitation?

Either way this module is *dumb* easy to use, and its amazing. Thank you for making a module like this.
Now for me to discover how i can stitch 3 gifs and make one giant one, if you want to help, that would be awesome, :P

**Comment by jtlapp** [comment]
I'm glad you find it easy to use!

`scale()` only takes integers because integer scaling is super-fast.

If you want general scaling, you can calculate the new, desired size, and hand that to Jimp's `scale()` method. Jimp doesn't have the super-fast integer scaling.

To concat three gifs, load each separately, concat their frame arrays, and encode the resulting array. Shouldn't be anything more too it.

If you're using GIFs that you pull off the web, bear in mind that each frame of a GIF can have a different size. That happens in GIFs that position sprites around on a background. I suspect those GIFs are rare, though.

**Comment by KingDGrizzle** [comment]
Awesome.

1. How do I pass it to Jimps scale? I'm *semi* new to this.

2. I don't want to concat, i want them one next to another, like `gifFrame1ForGif1 gifFrame1forGif2` etc. Probably doable with loops

**Comment by jtlapp** [comment]
1. You'll need to create a new Jimp object for each GIF frame and call `jimp.scale()` on that object. See [here](https://github.com/jtlapp/gifwrap#leveraging-jimp) for how to convert frames back and forth between Jimp and gifwrap.
2. Yeah, a loop should do it. You'll need to take care if the GIFs have different numbers of frames.

**Comment by KingDGrizzle** [comment]
Ouchy. I seem to have hit a color limitation 😛 
`Frame 3 uses more than 256 color indexes`

Welp, time to figure that one out, altough I'm lost as a rock

**Comment by jtlapp** [comment]
Your code looks good!

How are you getting more than 256 colors in one frame? Loading from something other than a GIF? Or maybe the Jimp `scale()` method is adding colors?

**Comment by KingDGrizzle** [comment]
Dunno. The gif in question is this `https://cdn.discordapp.com/emojis/399303426573467658.gif`, then using a GifCodec to decode, scale and re-encode

**Comment by jtlapp** [comment]
Maybe use Jimp to save frame 3 (after scaling) to a PNG, then load it into a graphics program to see if it looks like it has more than 256 colors. The program might even make a palette with a color count.

I guess gifwrap could use a utility for shrinking the color count of a frame to 256.

**Comment by KingDGrizzle** [comment]
Huh. Frames 1 and 2 are just blank (fully transparent but Windows), then frame 3 is just ![image](http://wait-it.works.wtf/vlag/2018/01/J7S998.png)

Doesn't seem that special. Some alpha and thats about it

**Comment by KingDGrizzle** [comment]
Okay.. yeah.. These gifs are in fact going over the colors as I've tried another one and same result..

Any way to make the colors go down to the required 256?

**Comment by jtlapp** [comment]
Yeah, I'm sure there's an algorithm out there somewhere. I can imagine a way I might do it, but I'm in the middle of something else right now. What's your time frame for getting this done?

**Comment by KingDGrizzle** [comment]
No need to rush, theres plenty time, and I have **loads** of other things to finish so I can place this on hold. Just ping me here (*or on Discord if you have it, I can give my Discord tag*), and I'll check it out. 😄 

And thanks for all the support! <3

**Comment by jtlapp** [comment]
Sure thing! It's a feature I could use too. I'll just respond here. Thanks!

**Comment by jtlapp** [comment]
Hey @KingDGrizzle, I've checked in color reduction tools. There are three algorithms:

- GifUtil.quantizeDekker()
- GifUtil.quantizeSorokin()
- GifUtil.quantizeWu()

It may be that any would work, or you may need to choose the one that works best. I dunno.

You can get these in v0.7, now published. HTH!

**Comment by KingDGrizzle** [comment]
Oo, awesome! I'll quickly update and try each of them and compare the results, using the one that provides the _best_ result for our needs.

I'll also take a look due to curiosity

**Comment by KingDGrizzle** [comment]
Oh myyyyyy, that didn't work as expected..
```js
decodedGif.frames.forEach(frame => {
	const tempJimp = new Jimp(1, 1, 0);
	tempJimp.bitmap = frame.bitmap;
	tempJimp.resize(128, AUTO);
	const tempImage = new BitmapImage(tempJimp.bitmap);
	console.log(`Pre quantize`);
	GifUtil.quantizeWu(tempImage);
	console.log(`Post quantize`);
    frame.bitmap = tempImage.bitmap;
});
```
Seems to have done nothing. Maybe return the modified image(s) after overwriting, so that we can then overwrite the buffer and pray to god it work

**Comment by jtlapp** [comment]
Try this:

```js
decodedGif.frames.forEach(frame => {
	const tempJimp = new Jimp(1, 1, 0);
	tempJimp.bitmap = frame.bitmap;
	tempJimp.resize(128, AUTO);
        frame.bitmap = tempJimp.bitmap; // use the resized bitmap
	console.log(`Pre quantize`);
	GifUtil.quantizeWu(frame); // use the modified frame
	console.log(`Post quantize`);
});
```

**Comment by KingDGrizzle** [comment]
Nop.. So weird.. Its like it ignores me resizing it. Confused af.

Also, I should really move this outside the main process. But till then, time to debug!

**Comment by jtlapp** [comment]
Also, to ensure color consistency across all of the frames -- so each frame doesn't get recolored differently -- I'd resize all of the frames and then hand that array of frames to the quantizer.

Whatever technique you used before to create an array of resized frames is all you need to do this time around. Just hand that array to the quantizer prior to encoding.

**Comment by KingDGrizzle** [comment]
Nop.. Still ignores it. So weird..
```js
decodedGif.frames.forEach(frame => {
	const tempJimp = new Jimp(1, 1, 0);
	tempJimp.bitmap = frame.bitmap;
	tempJimp.resize(128, AUTO);
	frame.bitmap = tempJimp.bitmap;
});
GifUtil.quantizeDekker(decodedGif.frames);
```

**Comment by jtlapp** [comment]
I ran the following. It took 10 or 15 minutes for Jimp to resize the image, and then the quantizer ran out of memory, resulting in a GC fault.

```js
const join = require('path').join;
const {GifUtil} = require('gifwrap');
const Jimp = require('jimp');

async function job(file) {
    const inputGif = await GifUtil.read(file);
    const frames = inputGif.frames;
    console.log(`read ${frames.length} frames`);
    frames.forEach((frame) => {
        const jimp = new Jimp(1, 1);
        jimp.bitmap = frame.bitmap;
        jimp.scale(128, 128);
        frame.bitmap = jimp.bitmap;
    });
    console.log(`quantizing...`);
    GifUtil.quantizeWu(frames);
    console.log(`writing...`);
    return GifUtil.write(frames, inputGif);
}

job(join(__dirname, 'hand.gif'))
.then((outputGif) => {
    console.log(`wrote ${outputGif.frames.length} frames`);
})
.catch((err) => {
    console.log(err.stack);
});
```

I'll play around to see if there's a better way to use resources.

**Comment by jtlapp** [comment]
All of the quantizers are crashing on your very first frame. As I recall, your first frame is all transparent. I wonder if that's the problem. Will test...

**Comment by jtlapp** [comment]
I found the problem. You were passing dimensions to the Jimp `scale()` method, but that method takes a float. Dimensions can be passed to `resize()` instead. My code above works with that change. You were processing 180 images of 8192x8192 pixels each!

Here's the working code in full:

```js
const join = require('path').join;
const {GifUtil} = require('gifwrap');
const Jimp = require('jimp');

async function job(fileIn, fileOut) {
    const inputGif = await GifUtil.read(fileIn);
    const frames = inputGif.frames;
    console.log(`read ${frames.length} frames`);
    
    frames.forEach((frame) => {
        const jimp = new Jimp(1, 1);
        jimp.bitmap = frame.bitmap;
        jimp.resize(128, 128); // OOPS!!!! should call .resize() not .scale()
        frame.bitmap = jimp.bitmap;
    });

    console.log(`quantizing...`);
    GifUtil.quantizeWu(frames);
    
    console.log(`writing...`);
    return GifUtil.write(fileOut, frames, inputGif);
}

job(join(__dirname, 'hand.gif'), join(__dirname, 'hand2.gif'))
.then((outputGif) => {
    console.log(`wrote ${outputGif.frames.length} frames`);
})
.catch((err) => {
    console.log(err.stack);
});
```

**Comment by KingDGrizzle** [comment]
Ha. I managed to do it now, using this code
```js
for (let decodedGif of decodedGifs) {
	const frames = decodedGif.frames;
	frames.forEach(frame => {
		const jimp = new Jimp(1, 1);
		jimp.bitmap = frame.bitmap;
		jimp.resize(128, AUTO);
		frame.bitmap = jimp.bitmap;
	});
	GifUtil.quantizeDekker(frames);
	const fileUUID = uuid();
	await GifUtil.write(`./Temp/${fileUUID}.gif`, frames, decodedGif);
	finishedGifs.push(fileUUID);
}
```

But good grief quantizing takes a while on many frames. So, time to see how to make it not quantize on the main process 👀 

Thank you so much for your help! <3
