### ISSUE TITLE
Question: Any way to resolve "writing interlaced GIFs is not supported" / Bypass the encoder

### ISSUE THREAD

**Issue by KingDGrizzle** [jtlapp/gifwrap#6]
Hello! It's me again :P

This time I have a question. I have this gif (`https://cdn.discordapp.com/emojis/422087870464131082.gif`), and I'd like to resize it, then save the buffer. The problem is that codec.encodeGif throws an error about the "interlaced GIFs". Is there any way for me to bypass the need of the encoder? Is there anything else I could try that would solve the issue?

Thanks :)

**Comment by jtlapp** [comment]
You must have loaded an interlaced GIF. Yes, all you need to do is turn off interlacing for each frame. So for each frame, set `frame.interlaced = false`. Lemme know whether that solve the problem.

**Comment by KingDGrizzle** [comment]
Well that was surprisingly simple! Thanks for that. 😅
