### ISSUE TITLE
question: Any way to bypass the 256 color check in GifCodec#encodeGif?

### ISSUE THREAD

**Issue by vladfrangu** [jtlapp/gifwrap#7]
Hello. It's a-me ~~Mario~~.

I've been, once again, messing around with GifWrap and well, again managing to reach the limit of colors. This time, I'm fully lost on how it happened, but it did, and it's sad. 

So, as the title suggests, are there any ways to bypass the need of quantizing frames? 

Thank chu!

EDIT: I am able to make it run on a child process,to quantize without blocking the main thread, but I asking in case there are any _other_ ways.

**Comment by jtlapp** [comment]
I'm not quite sure what you're asking. If you're asking whether there's a way to write a GIF with more than 256 colors, the answer is no, gives have at most 256 colors.

If you're asking for another way to reduce the color count, you could invent your own algorithm, but it is a tricky thing to do. The author of the quantization algorithm that gifwrap depends on has recently revised the module, and it may be faster now or perhaps have more options. Updating gifwrap to use the new algorithm may provide improvement -- I don't know. I'm not able to work on this right now, though.

**Comment by KingDGrizzle** [comment]
Alright, that's fine. I'll see what I can do. Although, you might also find this interesting, but just resizing the gif that seems to cause the issue works when it is standalone, but breaks when combined with other gif frames (aka throws 256 color error). So, who knows. I'll see if I can debug it further.

**Comment by jtlapp** [comment]
I should clarify that GIFs have at most 256 colors per frame. However, you can force the encoder to use 256 colors across all frames when possible, to encode at most 256 colors across all frames, or to encode 256 per frame.  These are the `colorScope` options passed to `encodeGif()`.

```
Gif.GlobalColorsPreferred = 0;
Gif.GlobalColorsOnly = 1;
Gif.LocalColorsOnly = 2;
```

If you read a GIF that encoded colors globally and pass the input GIF spec to the output encoder, it will try to encode them globally again. You may want to override that with one of the above options.

**Comment by redserpent7** [comment]
Anyway to fix this or at least quantize the output gif.

I am facing this issue when trying to resize a gif image by utilizing Jimp.

**Comment by jtlapp** [comment]
> Anyway to fix this or at least quantize the output gif.
> I am facing this issue when trying to resize a gif image by utilizing Jimp.

Jimp adds colors when resizing. If you resize using Jimp, you'll need to reduce the number of colors with one of the `quantize*()` methods before writing out the gif.

**Comment by jtlapp** [comment]
I'm assuming you've got this figured out now.
